language: node_js

node_js:
  - "10"

cache:
  directories:
  - node_modules

install: case $TRAVIS_BRANCH in greenkeeper*) npm i;; *) npm ci;; esac;

before_script: npm run bootstrap

script:
  - npm run test

after_script: npm run coverage
