language: node_js

node_js:
  - "10"

cache:
  directories:
  - node_modules

install:
  - npm install
  - npm run bootstrap

script:
  - npm run lint
  - npm run test

after_script: npm run coverage
