language: node_js

node_js:
  - "10"

cache:
  directories:
  - node_modules

jobs:
  include:
    - stage: test
      script:
        - npm install
        - npm run bootstrap
        - npm run test
        - npm run coverage
