language: node_js

node_js:
  - "10"

cache:
  directories:
  - node_modules

before_install:
  - chmod +x scripts/install.sh

install:
  - npm run install

script:
  - npm run test

after_script: npm run coverage
